### ISSUE TITLE
Add documentation on Wheatley to the main 'Help' page

### ISSUE THREAD

**Issue by BrynMarieR** [lelandpaul/ringingroom#174]
@kneasle

**Comment by BrynMarieR** [comment]
Wheatley help should also be added to the 'help' dropdown on the tower page

**Comment by kneasle** [comment]
Yep I can do this - could you assign me to this?

Also, it turns out that my exams next week actually count towards my degree so I'm a little bit preoccupied by them...

**Comment by BrynMarieR** [comment]
Assigned! Good luck with your exams :)

**Comment by kneasle** [comment]
Thanks! `:)`

**Comment by kneasle** [comment]
This should have been closed by #220, right?

**Comment by BrynMarieR** [comment]
👍
