### ISSUE TITLE
Wheatley box should have > v arrow to expand/contract

### ISSUE THREAD

**Issue by BrynMarieR** [lelandpaul/ringingroom#175]
As with the chat box and the user box so people have a visual cue that it can be closed

@kneasle @lelandpaul

**Comment by kneasle** [comment]
I thought it does:
![image](https://user-images.githubusercontent.com/32932209/95015560-7b88b900-0645-11eb-9ade-049a410ef136.png)

**Comment by BrynMarieR** [comment]
<img width="366" alt="Screen Shot 2020-10-04 at 8 37 18 AM" src="https://user-images.githubusercontent.com/7773989/95015771-d2c66380-061c-11eb-8588-468a87175ba3.png">

**Comment by BrynMarieR** [comment]
Is it hard-coded to be grey...? That would make sense for it only showing up in Dark Mode...

**Comment by kneasle** [comment]
OK that's interesting I thought I'd just copied and pasted the code from the chatbox.  I'll give it a look...

**Comment by kneasle** [comment]
![image](https://user-images.githubusercontent.com/32932209/95025501-0c7d8580-0682-11eb-86e1-2f68b0b56ba2.png)

**Comment by BrynMarieR** [comment]
I am indeed using Chrome. I don't have it up right now but I don't think this is urgent/very important, so we can probably proceed without for now if we can't track down the issue.

**Comment by lelandpaul** [comment]
Found the issue: The arrow only shows up once you recompile the Sass. :)
