### ISSUE TITLE
Half-muffled sound

### ISSUE THREAD

**Issue by lelandpaul** [lelandpaul/ringingroom#70]
Add an option for half-muffled sound (probably just lower-volume on the muffled strokes). This should probably go along with the volume slider in the tower controls; see #69 .

**Comment by JPumphrey** [comment]
If we have bandwidth, we could add a single 'thump' audio to be the muffled stroke for all the bells. Might be more authentic

**Comment by lelandpaul** [comment]
It would be good. I may reach out to Bill Hibbert (who supplied our current tower-bell recordings) to see if he has good muffled recordings.

**Comment by JPumphrey** [comment]
I can simulate one in the meantime and if/when you get a better one you can sub it in

**Comment by JPumphrey** [comment]
Is there documentation for how the sound files are generated?

**Comment by BrynMarieR** [comment]
We use [howler.js](https://github.com/goldfire/howler.js/) to play the sounds; the actual bell recordings themselves are stored in app/static/audio -- processing was done manually to clip/suppress sound after 1 second.

(in other words, nope, sorry about that :/ )

**Comment by lelandpaul** [comment]
The main sound files are generated with [audiosprite](https://github.com/tonistiigi/audiosprite)

**Comment by JPumphrey** [comment]
I guess more directly my question was "what is the process for adding a new sound?"

**Comment by BrynMarieR** [comment]
Ah! So assuming half-muffled only makes sense for tower bells: you'd add new audio files directly to app/static/audio/processed_audio/tower. You'd name them appropriately, probably "halfmuffled-2.wav" or whatever.

You take those files, along with the other tower bell audio files, and combine them into a single sprite using the directions found on [audiosprite](https://github.com/tonistiigi/audiosprite), making sure to drop the resultant *json, *ac3, *m4a, *mp3, *ogg files into the repo. Make sure the json is formatted for howler2.

Then you will need to add some connect-y javascript bits to hook up the sounds to a new audio mode called "half-muffled" (or whatever). This includes modifying app/static/audio.js as well as app/static/ringingroom.js.

An additional tricky point is that currently the bell sound is the same on both hand and backstroke, so there is no code to differentiate between sounds made at hand and back. That would need to be added in.

**Comment by BrynMarieR** [comment]
Hey, we did this one!
