### ISSUE TITLE
Increase gap between treble and tenor

### ISSUE THREAD

**Issue by BrynMarieR** [lelandpaul/ringingroom#71]
To make for better rope-sight, increase gap between treble and tenor. This may require addition of a hidden, invisible/noninteractive "bell" to be compatible with CSS layout.

**Comment by JPumphrey** [comment]
I'll take a look at this

**Comment by JPumphrey** [comment]
Actually I don't have time right now, unassigning.

**Comment by BrynMarieR** [comment]
Deciding unnecessary after changing treble's color (tower bell mode)
